# Generated by Django 4.0.8 on 2022-11-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_order',
            field=models.CharField(max_length=300),
        ),
    ]
